### ISSUE TITLE
Using Project

### ISSUE THREAD

**Issue by CryptoDevving** [jrvansuita/crime-pay#1]
Hello,

Am I able to use this project? I want to fork, edit and deploy it both in a test and production environment for my project.

**Comment by jrvansuita** [comment]
Hi, of course! This is an open source project. Just mention or give credits for this repo and you will be good.
If you can share some infos on what is you project, and how will you use it, I will be happy to know.

**Comment by CryptoDevving** [comment]
I wanted to adapt it into a monster collection game with a focus on life simulation. Think a cross between the Sims and Pokemon.

Edit: Thank you so much.
