### ISSUE TITLE
DUVIDA - Como rodar em localhost?

### ISSUE THREAD

**Issue by future2back** [jrvansuita/crime-pay#2]
Fala amigo bom dia, tudo bem? Voce poderia postar os arquivos .sol e explicar como faço para rodar em localhost por favor? Estou estudando Solidity e ver um projeto real em funcionamento me ajuda bastante.

Obrigado, parabéns pelo projeto e sucesso.

**Comment by jrvansuita** [comment]
Não implementei contrato, não cheguei a criar uma coin. 

Obrigado.
